language: python
python:
  - 3.8
install:
  - pip install -q pipenv codecov
  - pipenv sync --dev
scripts:
  - flake8
  - pytest libpythonpro_ravellys --cov=libpythonpro_ravellys
after_success:
  - codecov